(function(g){var window=this;var l6=function(a,b){var c=[];g.jk(b,function(a){var b;try{b=g.Zl.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.u(b)?g.Lh(b)&&c.push(a):c.push(a)},a);
return c},m6=function(a,b){var c=l6(a,b);
(0,g.J)(c,function(a){g.Zl.prototype.remove.call(this,a)},a)},n6=function(a,b){g.KP.call(this,g.K("YTP_MDX_TITLE"),0,a,b);
this.R=a;this.F={};this.N(a,"onMdxReceiversChange",this.J);this.N(a,"presentingplayerstatechange",this.J);this.J()},o6=function(){var a=g.kt;
m6(a,a.g.md(!0))},p6=function(){this.g=[];
this.o=[]},q6=function(a){return a.J?a.F+((0,g.C)()-a.A)/1E3:a.F},r6=function(a){g.yi("cloudview",a)},s6=function(a){g.js.call(this,"ScreenServiceProxy");
this.Ub=a;this.o=[];this.o.push(this.Ub.$_s("screenChange",(0,g.A)(this.bE,this)));this.o.push(this.Ub.$_s("onlineScreenChange",(0,g.A)(this.lB,this)))},t6=function(a){r6("setApiReady_ "+a);
g.w("yt.mdx.remote.cloudview.apiReady_",a,void 0)},u6=function(){return g.x("yt.mdx.remote.cloudview.instance_")},v6=function(a){g.Tq[a]&&(a=g.Tq[a],(0,g.J)(a,function(a){g.Rq[a]&&delete g.Rq[a]}),a.length=0)},w6=function(){return g.x("yt.mdx.remote.connection_")},x6=function(a){g.w("yt.mdx.remote.connectData_",a,void 0)},y6=function(a){g.w("yt.mdx.remote.currentScreenId_",a,void 0)},z6=function(){return g.x("yt.mdx.remote.currentScreenId_")},B6=function(){if(!A6){var a=g.x("yt.mdx.remote.screenService_");
A6=a?new s6(a):null}return A6},C6=function(a){g.w("yt.mdx.remote.cloudview.initializing_",a,void 0)},D6=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},E6=function(a){r6("setCastInstalled_ "+a);
g.mt("yt-remote-cast-installed",a)},F6=function(a){g.yi("cloudview",a)},G6=function(a,b){u6().init(a,b)},H6=function(){return!!g.nt("yt-remote-cast-installed")},J6=function(){r6("dispose");
var a=u6();a&&a.dispose();g.w("yt.mdx.remote.cloudview.instance_",null,void 0);t6(!1);g.Vq(I6);I6.length=0},K6=function(){var a=window.document.createElement("a");
g.Lm(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.kc(a)},L6=function(a,b){var c=window.document.createElement("script");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
c.src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js";var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},M6=function(a){var b=g.Qq();
if(b)if(b.clear(a),a)v6(a);else for(var c in g.Tq)v6(c)},N6=function(){return g.x("yt.mdx.remote.channelParams_")||{}},P6=function(a){var b=w6();
x6(null);a||y6("");g.w("yt.mdx.remote.connection_",a,void 0);O6&&((0,g.J)(O6,function(b){b(a)}),O6.length=0);
b&&!a?g.Xq("yt-remote-connection-change",!1):!b&&a&&g.Xq("yt-remote-connection-change",!0)},Q6=function(){return g.x("yt.mdx.remote.connectData_")},R6=function(){var a=z6();
if(!a)return null;var b=B6().Ic();return g.Hk(b,a)},S6=function(a,b){E6(!0);
C6(!1);G6(a,function(a){a?(t6(!0),g.Wq("yt-remote-cast2-api-ready")):(F6("Failed to initialize cast API."),E6(!1),g.ot("yt-remote-cast-available"),g.ot("yt-remote-cast-receiver"),J6());b(a)})},T6=function(){return H6()?u6()?u6().getCastSession():(F6("getCastSelector: Cast is not initialized."),null):(F6("getCastSelector: Cast API is not installed!"),null)},U6=function(){var a=K6(),b=window.document.getElementById(a),c=b&&g.yc(b,"loaded");
c||b&&!c||(b=L6(a,function(){g.yc(b,"loaded")||(g.zc(b,"loaded","true"),g.Wq(a),g.Gj(g.Ca(M6,a),0))}))},V6=function(a){return(0,g.M)(a,function(a){return{key:a.id,
name:a.name}})},W6=function(){if(g.KU){var a=2,b=g.Ha(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;g.Na("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",g.Ka,c)}},Y6=function(a,b){z6();
R6()&&R6();y6(a.id);var c=new g.qH(X6,a,N6());c.connect(b,Q6());c.subscribe("beforeDisconnect",function(a){g.Xq("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){w6()&&(w6(),P6(null))});
P6(c)},Z6=function(){var a=g.Au();
if(!a)return null;var b=B6().Ic();return g.Hk(b,a)},$6=function(a){g.yi("remote",a)},a7=function(){var a=w6();
return!!a&&3!=a.getProxyState()},b7=function(){D6()?u6().stopSession():F6("stopSession called before API ready.");
var a=w6();a&&(a.disconnect(1),P6(null))},c7=function(){var a;
a=B6().Ub.$_gos();var b=R6();b&&w6()&&(g.Gk(a,b)||a.push(b));return V6(a)},f7=function(a,b){g.Pq.call(this);
this.g=0;this.B=a;this.D=[];this.C=new p6;this.A=this.o=null;this.J=(0,g.A)(this.Lz,this);this.F=(0,g.A)(this.gh,this);this.G=(0,g.A)(this.Kz,this);this.K=(0,g.A)(this.Yz,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Jm,this),d7(this))):c=3;0!=c&&(b?this.Jm(c):g.Gj((0,g.A)(function(){this.Jm(c)},this),0));
var d=T6();d&&e7(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},g7=function(a){return new g.he(a.B.getPlayerContextData())},j7=function(a,b,c,d,e){var f=g7(a),k=e||f.listId;
d=d||0;var l={videoId:b,currentIndex:d};g.le(f,b,d);g.u(c)&&(g.je(f,c),l.currentTime=c);g.u(k)&&(l.listId=k);h7(a,"setPlaylist",l);e||i7(a,f)},d7=function(a){(0,g.J)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.Ca(this.zB,a),this))},a)},k7=function(a){(0,g.J)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},l7=function(a,b){50>a.C.Fc()&&a.C.o.push(b)},m7=function(a,b,c){var d=g7(a);
g.je(d,c);-1E3!=d.g&&(d.g=b);i7(a,d)},h7=function(a,b,c){a.B.sendMessage(b,c)},i7=function(a,b){k7(a);
a.B.setPlayerContextData(g.me(b));d7(a)},e7=function(a,b){a.A&&(a.A.removeUpdateListener(a.J),a.A.removeMediaListener(a.F),a.gh(null));
a.A=b;a.A&&(n7("Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.J),a.A.addMediaListener(a.F),a.A.media.length&&a.gh(a.A.media[0]))},o7=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=g7(a);b.contentId!=d.videoId&&n7("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;g.je(d,a.o.getEstimatedTime());i7(a,d)}else n7("No cast media video. Ignoring state update.")},n7=function(a){g.yi("CP",a)},p7=function(a,b,c){return(0,g.A)(function(a){this.xb("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.xb("Retrying "+b+" using MDx browser channel."),h7(this,b,c))},a)},q7=function(a){var b=!1;
u6()||(a=new g.dF(a),a.subscribe("yt-remote-cast2-availability-change",function(a){g.mt("yt-remote-cast-available",a);g.Xq("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){r6("onReceiverSelected: "+a.friendlyName);
g.mt("yt-remote-cast-receiver",a);g.Xq("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){r6("onReceiverResumed: "+a.friendlyName);
g.mt("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){r6("onSessionChange: "+g.Ji(a));
a||g.ot("yt-remote-cast-receiver");g.Xq("yt-remote-cast2-session-change",a)}),g.w("yt.mdx.remote.cloudview.instance_",a,void 0),b=!0);
r6("cloudview.createSingleton_: "+b);return b},r7=function(){var a=0<=g.bc.search(/\ (CrMo|Chrome|CriOS)\//);
return g.no||a},s7=function(a,b){D6()?u6().setConnectedScreenStatus(a,b):F6("setConnectedScreenStatus called before ready.")},t7=function(){r6("clearCurrentReceiver");
g.ot("yt-remote-cast-receiver")},u7=function(){if(0<=window.navigator.userAgent.indexOf("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){W6();a({command:"cast.sender.init"});return}}if(window.chrome)if(W6(),a=window.navigator.userAgent,0<=a.indexOf("Android")&&0<=a.indexOf("Chrome/")&&window.navigator.presentation){var a="",b=g.Fa();55<=b?a="55":50<=b&&(a="50");g.Na("//www.gstatic.com/eureka/clank"+a+g.La,g.Ka)}else g.Oa(0);else g.Ka()},v7=function(a){a?(g.mt("yt-remote-session-app",a.app),g.mt("yt-remote-session-name",a.name)):(g.ot("yt-remote-session-app"),g.ot("yt-remote-session-name"));
g.w("yt.mdx.remote.channelParams_",a,void 0)},w7=function(){var a=N6();
if(g.Db(a)){var a=g.zu(),b=g.nt("yt-remote-session-name")||"",c=g.nt("yt-remote-session-app")||"",a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.w("yt.mdx.remote.channelParams_",a,void 0)}},x7=function(){var a=Z6();
a?($6("Resume connection to: "+g.Ji(a)),Y6(a,0)):(g.Lu(),t7(),$6("Skipping connecting because no session screen found."))},y7=function(a){$6("remote.onCastSessionChange_: "+g.Ji(a));
if(a){var b=R6();b&&b.id==a.id?s7(b.id,"YouTube TV"):(b&&b7(),Y6(a,1))}else w6()&&b7()},z7=function(){var a=c7(),b=R6();
b||(b=Z6());return g.Je(a,function(a){return b&&g.Ei(b,a.key)?!0:!1})},A7=function(){var a=g.nt("yt-remote-cast-receiver");
return a?a.friendlyName:null},B7=function(a,b,c,d){r7()?q7(b)&&(C6(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?S6(a,c):(window.__onGCastApiAvailable=function(b,d){b?S6(a,c):(F6("Failed to load cast API: "+d),E6(!1),C6(!1),g.ot("yt-remote-cast-available"),g.ot("yt-remote-cast-receiver"),J6(),c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):U6():u7())):r6("Cannot initialize because not running Chrome")},C7=function(a){this.port=
this.A="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.Jf(a)||"";b&&(this.port=":"+b);this.A=g.If(a)||"";a=g.bc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.jc(a,"10.0")&&(this.o=!1))},D7=function(){var a=z7();
!a&&H6()&&A7()&&(a={key:"cast-selector-receiver",name:A7()});return a},E7=function(){var a=c7();
H6()&&g.nt("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},G7=function(a){var b={device:"Desktop",
app:"youtube-desktop"};g.kt&&o6();g.Du();X6||(X6=new C7,g.Nu()&&(X6.g="/api/loungedev"));O6||(O6=g.x("yt.mdx.remote.deferredProxies_")||[],g.w("yt.mdx.remote.deferredProxies_",O6,void 0));w7();var c=B6();if(!c){var d=new g.sB(X6);g.w("yt.mdx.remote.screenService_",d,void 0);c=B6();B7(a,d,function(a){a?z6()&&s7(z6(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){g.Xq("yt-remote-receiver-availability-change")})},!(!b||!b.loadCastApiSetupScript))}b&&!g.x("yt.mdx.remote.initialized_")&&(g.w("yt.mdx.remote.initialized_",
!0,void 0),$6("Initializing: "+g.ib(b)),F7.push(g.Uq("yt-remote-cast2-availability-change",function(){g.Xq("yt-remote-receiver-availability-change")})),F7.push(g.Uq("yt-remote-cast2-receiver-selected",function(){x6(null);
g.Xq("yt-remote-auto-connect","cast-selector-receiver")})),F7.push(g.Uq("yt-remote-cast2-receiver-resumed",function(){g.Xq("yt-remote-receiver-resumed","cast-selector-receiver")})),F7.push(g.Uq("yt-remote-cast2-session-change",y7)),F7.push(g.Uq("yt-remote-connection-change",function(a){a?s7(z6(),"YouTube TV"):Z6()||(s7(null,null),t7())})),a=N6(),b.isAuto&&(a.id+="#dial"),g.Zf("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,$6(" -- with channel params: "+g.ib(a)),v7(a),
c.start(),z6()||x7())},H7=function(){H6()?u6()?D6()?(r6("Requesting cast selector."),u6().requestSession()):(r6("Wait for cast API to be ready to request the session."),I6.push(g.Uq("yt-remote-cast2-api-ready",H7))):F6("requestCastSelector: Cast is not initialized."):F6("requestCastSelector: Cast API is not installed!")},I7=function(a,b,c){g.G.call(this);
this.J=a;this.R=b;b.addEventListener("onVolumeChange",this.Vi,this);b.addEventListener("onCaptionsTrackListChanged",this.rr,this);b.addEventListener("captionschanged",this.fr,this);b.addEventListener("captionssettingschanged",this.rm,this);b.addEventListener("videoplayerreset",this.ih,this);b.addEventListener("mdxautoplaycancel",this.Wn,this);this.C=!1;this.g=c;c.subscribe("proxyStateChange",this.Br,this);c.subscribe("remotePlayerChange",this.hh,this);c.subscribe("remoteQueueChange",this.ih,this);
c.subscribe("autoplayUpNext",this.br,this);c.subscribe("previousNextChange",this.yr,this);c.subscribe("nowAutoplaying",this.ur,this);c.subscribe("autoplayDismissed",this.ar,this);this.suggestion=null;this.D=new g.dD(64);this.o=new g.S(this.Is,500,this);g.H(this,this.o);this.A=new g.S(this.Ks,1E3,this);g.H(this,this.A);this.B={};this.G=new g.S(this.Xs,1E3,this);g.H(this,this.G);this.F=new g.ew(this.QF,1E3,this);g.H(this,this.F);this.K=g.pa;this.rm();this.ih();this.hh()},J7=function(a,b){var c=a.J,
d=a.R.getVideoData().lengthSeconds;
c.J=b||0;c.g.P("progresssync",b,d)},L7=function(a){J7(a,0);
a.o.stop();K7(a,new g.dD(64))},O7=function(a,b){if(M7(a)&&!a.C){var c=null;
b&&(c={style:a.R.Bh()},g.Ib(c,b));a.g.Es(N7(a),c);a.B=g7(a.g).o}},P7=function(a,b){var c=a.R.Xd();
c?j7(a.g,N7(a),b,c.Va,c.listId.toString()):j7(a.g,N7(a),b);K7(a,new g.dD(1))},Q7=function(a,b){if(b){var c=a.R.Wb("captions","tracklist",{Bp:1});
c&&c.length?(a.R.jd("captions","track",b),a.C=!1):(a.R.yh("captions"),a.C=!0)}else a.R.jd("captions","track",{})},M7=function(a){return g7(a.g).videoId==N7(a)},N7=function(a){return a.R.getVideoData().videoId},K7=function(a,b){a.A.stop();
var c=a.D;if(!g.jD(c,b)){var d=g.F(b,2);if(d!=g.F(a.D,2)){var e=a.R;(e=g.Y(e.app,e.playerType||1))&&g.QM(e,d)}a.D=b;R7(a.J,c,b)}},T7=function(a){g.U.call(this,{H:"div",
T:"ytp-remote",M:[{H:"div",T:"ytp-remote-display-status",M:[{H:"div",T:"ytp-remote-display-status-icon",M:[g.Wh()]},{H:"div",T:"ytp-remote-display-status-text",M:["{{statustext}}"]}]}]});this.g=new g.az(this,250);g.H(this,this.g);this.A=a;this.N(a,"presentingplayerstatechange",this.B);S7(this,g.MB(a))},S7=function(a,b){if(3==a.A.Ea()){var c={RECEIVER_NAME:a.A.Wb("remote","currentReceiver").name},c=g.F(b,128)?g.K("YTP_MDX_STATUS_ERROR_2",c):b.wb()||g.F(b,4)?g.K("YTP_MDX_STATUS_PLAYING_2",c):g.K("YTP_MDX_STATUS_CONNECTED_2",
c);
a.oa("statustext",c);a.g.show()}else g.cz(a.g)},U7=function(a){g.ws.call(this,a);
this.A={key:g.Fk(),name:g.K("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.K=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.dD(64);this.J=0;var b=g.SN(a).C;b&&(b=b.A&&b.A.g)&&(b=new n6(a,b),g.H(this,b));b=new T7(a);g.H(this,b);g.UG(a,b.element,5)},R7=function(a,b,c){a.F=c;
a.g.P("presentingplayerstatechange",new g.id(c,b))},V7=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)b7();
else{a.B=b;var c;c=a.g.getPlaylistId();var d=a.g.getVideoData().videoId;if(c||d){var e,f=a.g.Xd();if(f){e=[];for(var k=0;k<f.getLength();k++)e[k]=f.vb(k).videoId}else e=[a.g.getVideoData().videoId];c={videoIds:e,listId:c,videoId:d,index:Math.max(a.g.xt(),0),currentTime:a.g.getCurrentTime()}}else c=null;$6("Connecting to: "+g.ib(b));"cast-selector-receiver"==b.key?(x6(c||null),c=c||null,D6()?u6().setLaunchParams(c):F6("setLaunchParams called before ready.")):!c&&a7()&&z6()==b.key?g.Xq("yt-remote-connection-change",
!0):(b7(),x6(c||null),c=B6().Ic(),(c=g.Hk(c,b.key))&&Y6(c,1))}};
g.p(n6,g.KP);n6.prototype.J=function(){var a=this.R.Wb("remote","receivers");a&&1<a.length&&!this.R.Wb("remote","quickCast")?(this.F=g.gf(a,this.B,this),g.MP(this,(0,g.M)(a,this.B)),a=this.R.Wb("remote","currentReceiver"),g.LP(this,this.B(a)),this.enable(!0)):this.enable(!1)};
n6.prototype.B=function(a){return a.key};
n6.prototype.qd=function(a){return"cast-selector-receiver"==a?g.K("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
n6.prototype.Zb=function(a){g.KP.prototype.Zb.call(this,a);this.R.jd("remote","currentReceiver",this.F[a]);this.A.rb()};
g.h=p6.prototype;g.h.Fc=function(){return this.g.length+this.o.length};
g.h.isEmpty=function(){return 0==this.g.length&&0==this.o.length};
g.h.clear=function(){this.g=[];this.o=[]};
g.h.contains=function(a){return g.Ne(this.g,a)||g.Ne(this.o,a)};
g.h.remove=function(a){var b;b=this.g;var c=(0,g.gV)(b,a);0<=c?(g.Qe(b,c),b=!0):b=!1;return b||g.Re(this.o,a)};
g.h.kb=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);for(var c=this.o.length,b=0;b<c;++b)a.push(this.o[b]);return a};
g.B(s6,g.js);g.h=s6.prototype;g.h.Ic=function(a){return this.Ub.$_gs(a)};
g.h.contains=function(a){return!!this.Ub.$_c(a)};
g.h.get=function(a){return this.Ub.$_g(a)};
g.h.start=function(){this.Ub.$_st()};
g.h.Aj=function(a,b,c){this.Ub.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Ub.$_r(a,b,c)};
g.h.tj=function(a,b,c,d){this.Ub.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.o.length;a<b;++a)this.Ub.$_ubk(this.o[a]);this.o.length=0;this.Ub=null;s6.Y.X.call(this)};
g.h.bE=function(){this.P("screenChange")};
g.h.lB=function(){this.P("onlineScreenChange")};
var A6=null,I6=[],O6=null,X6=null;g.B(f7,g.Pq);g.h=f7.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.pa,p7(this,"play")):h7(this,"play"),m7(this,1,g.ke(g7(this))),this.P("remotePlayerChange")):l7(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.pa,p7(this,"pause")):h7(this,"pause"),m7(this,2,g.ke(g7(this))),this.P("remotePlayerChange")):l7(this,this.pause)};
g.h.ht=function(a){if(1==this.g){if(this.o){var b=g7(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.wb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.pa,p7(this,"seekTo",{newTime:a}))}else h7(this,"seekTo",{newTime:a});m7(this,3,a);this.P("remotePlayerChange")}else l7(this,g.Ca(this.ht,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.pa,p7(this,"stopVideo")):h7(this,"stopVideo");var a=g7(this);a.index=-1;a.videoId="";g.ie(a);i7(this,a);this.P("remotePlayerChange")}else l7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=g7(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.A)(function(){n7("set receiver volume: "+d)},this),(0,g.A)(function(){this.xb("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.A)(function(){n7("set receiver muted: "+b)},this),(0,g.A)(function(){this.xb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);h7(this,"setVolume",e)}c.muted=b;c.volume=a;i7(this,c)}else l7(this,g.Ca(this.setVolume,a,b))};
g.h.Es=function(a,b){if(1==this.g){var c=g7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.ib(b.style),g.Ib(d,c.o));h7(this,"setSubtitlesTrack",d);i7(this,c)}else l7(this,g.Ca(this.Es,a,b))};
g.h.Im=function(a,b){if(1==this.g){h7(this,"setAudioTrack",{videoId:a,audioTrackId:b.Pb.id});var c=g7(this);c.audioTrackId=b.Pb.id;i7(this,c)}else l7(this,g.Ca(this.Im,a,b))};
g.h.gt=function(a,b){if(1==this.g){if(a&&b){var c=g7(this);g.le(c,a,b);i7(this,c)}h7(this,"previous")}else l7(this,g.Ca(this.gt,a,b))};
g.h.dt=function(a,b){if(1==this.g){if(a&&b){var c=g7(this);g.le(c,a,b);i7(this,c)}h7(this,"next")}else l7(this,g.Ca(this.dt,a,b))};
g.h.Fo=function(){1==this.g?h7(this,"dismissAutoplay"):l7(this,this.Fo)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.P("proxyStateChange",a,this.g)}f7.Y.dispose.call(this)};
g.h.X=function(){k7(this);this.B=null;this.C.clear();e7(this,null);f7.Y.X.call(this)};
g.h.Jm=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.P("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)b=a=this.C,0==b.g.length&&(b.g=b.o,b.g.reverse(),b.o=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.zB=function(a,b){this.P(a,b)};
g.h.Lz=function(a){if(!a)this.gh(null),e7(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=g7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)n7("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,i7(this,b)}};
g.h.gh=function(a){n7("Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),o7(this),this.P("remotePlayerChange")};
g.h.Kz=function(a){a?(o7(this),this.P("remotePlayerChange")):this.gh(null)};
g.h.Yz=function(){var a=T6();a&&e7(this,a)};
g.h.xb=function(a){g.yi("CP",a)};
var F7=[];g.h=C7.prototype;g.h.mf=function(a,b,c){var d=this.g;if(g.u(c)?c:this.o)d="https://"+this.A+this.port+this.g;return g.Rf(d+a,b||{})};
g.h.Hm=function(a,b,c,d){c={format:"JSON",method:"POST",context:this,timeout:5E3,withCredentials:!1,Ya:g.Ca(this.WD,c,!0),onError:g.Ca(this.VD,d),Yb:g.Ca(this.XD,d)};b&&(c.ib=b,c.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Tu(a,c)};
g.h.WD=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g.h.VD=function(a,b){a(Error("Request error: "+b.status))};
g.h.XD=function(a){a(Error("request timed out"))};
g.B(I7,g.G);g.h=I7.prototype;
g.h.X=function(){I7.Y.X.call(this);this.o.stop();this.A.stop();this.K();this.R.removeEventListener("onVolumeChange",this.Vi,this);this.R.removeEventListener("onCaptionsTrackListChanged",this.rr,this);this.R.removeEventListener("captionschanged",this.fr,this);this.R.removeEventListener("videoplayerreset",this.ih,this);this.R.removeEventListener("captionssettingschanged",this.rm,this);this.R.removeEventListener("mdxautoplaycancel",this.Wn,this);this.g.unsubscribe("proxyStateChange",this.Br,this);this.g.unsubscribe("remotePlayerChange",
this.hh,this);this.g.unsubscribe("remoteQueueChange",this.ih,this);this.g.unsubscribe("autoplayUpNext",this.br,this);this.g.unsubscribe("previousNextChange",this.yr,this);this.g.unsubscribe("nowAutoplaying",this.ur,this);this.g.unsubscribe("autoplayDismissed",this.ar,this);this.g=this.J=null};
g.h.bu=function(a,b){2==this.g.g||(M7(this)?this.uw.apply(this,arguments):this.qw.apply(this,arguments))};
g.h.fr=function(a){this.bu("control_subtitles_set_track",g.Db(a)?null:a)};
g.h.rm=function(){var a=this.R.Wb("captions","track");g.Db(a)||O7(this,a)};
g.h.qw=function(a,b){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":P7(this,this.R.getCurrentTime());break;case "control_seek":P7(this,c[0]);break;case "control_subtitles_set_track":O7(this,c[0]);break;case "control_set_audio_track":c=c[0],M7(this)&&this.g.Im(N7(this),c)}};
g.h.uw=function(a,b){if(1081!=g7(this.g).g||"control_seek"!=a){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":g7(this.g).wb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.F.Yf(c[0],c[1]);break;case "control_subtitles_set_track":O7(this,c[0]);break;case "control_set_audio_track":c=c[0],M7(this)&&this.g.Im(N7(this),c)}}};
g.h.Vi=function(a){if(M7(this)){this.g.unsubscribe("remotePlayerChange",this.hh,this);var b=Math.round(a.volume);a=!!a.muted;var c=g7(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.G.start();this.g.subscribe("remotePlayerChange",this.hh,this)}};
g.h.rr=function(){g.Db(this.B)||Q7(this,this.B);this.C=!1};
g.h.Br=function(a,b){this.A.stop();2==b&&this.Ks()};
g.h.hh=function(){if(M7(this)){this.o.stop();var a=g7(this.g);switch(a.g){case 1081:K7(this,new g.dD(8));break;case 1:this.Is();K7(this,new g.dD(8));break;case 1083:case 3:K7(this,new g.dD(9));break;case 0:K7(this,new g.dD(2));this.F.stop();J7(this,this.R.getVideoData().lengthSeconds);break;case 1082:K7(this,new g.dD(4));break;case 2:K7(this,new g.dD(4));J7(this,g.ke(a));break;case -1:K7(this,new g.dD(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.K("YTP_MDX_PLAYER_ERROR")},K7(this,
new g.dD(128,a))}var a=g7(this.g).o,b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.B=a,Q7(this,a));a=g7(this.g);-1==a.volume||Math.round(this.R.getVolume())==a.volume&&this.R.oc()==a.muted||this.G.isActive()||this.Xs()}else L7(this)};
g.h.yr=function(){this.R.P("mdxpreviousnextchange")};
g.h.ih=function(){M7(this)||L7(this)};
g.h.Wn=function(){this.g.Fo()};
g.h.br=function(a){a&&(a=g.Tu("/watch_queue_ajax",{method:"GET",Qb:{action_get_watch_queue_item:1,video_id:a},Ya:(0,g.A)(this.uC,this)}))&&(this.K=(0,g.A)(a.abort,a))};
g.h.uC=function(a,b){var c=new g.SL({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.R.P("mdxautoplayupnext",c)};
g.h.ur=function(a){(0,window.isNaN)(a)||this.R.P("mdxnowautoplaying",a)};
g.h.ar=function(){this.R.P("mdxautoplaycanceled")};
g.h.QF=function(a,b){-1==g7(this.g).g?P7(this,a):b&&this.g.ht(a)};
g.h.Xs=function(){if(M7(this)){var a=g7(this.g);this.R.removeEventListener("onVolumeChange",this.Vi,this);a.muted?this.R.mute():this.R.se();this.R.setVolume(a.volume);this.R.addEventListener("onVolumeChange",this.Vi,this)}};
g.h.Is=function(){this.o.stop();if(!this.g.ia()){var a=g7(this.g);a.wb()&&K7(this,new g.dD(8));J7(this,g.ke(a));this.o.start()}};
g.h.Ks=function(){this.A.stop();this.o.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.A.start()};g.p(T7,g.U);T7.prototype.B=function(a){S7(this,a.state)};g.B(U7,g.ws);g.h=U7.prototype;g.h.create=function(){G7("embedded"==g.W(this.g).g);this.D.push(g.Uq("yt-remote-before-disconnect",this.Iz,this));this.D.push(g.Uq("yt-remote-connection-change",this.IB,this));this.D.push(g.Uq("yt-remote-receiver-availability-change",this.zr,this));this.D.push(g.Uq("yt-remote-auto-connect",this.GB,this));this.D.push(g.Uq("yt-remote-receiver-resumed",this.FB,this));this.zr()};
g.h.load=function(){this.g.ik();U7.Y.load.call(this);this.C=new I7(this,this.g,this.o);var a;a=(a=Q6())?a.currentTime:0;var b=a7()?new f7(w6(),void 0):null;0==a&&b&&(a=g.ke(g7(b)));0!=a&&(this.J=a||0,this.g.P("progresssync",a,void 0));R7(this,this.F,this.F);g.bT(this.g.app,6)};
g.h.unload=function(){this.g.P("mdxautoplaycanceled");this.B=this.A;g.Ld(this.C,this.o);this.o=this.C=null;U7.Y.unload.call(this);g.bT(this.g.app,5)};
g.h.X=function(){g.Vq(this.D);U7.Y.X.call(this)};
g.h.Fh=function(a,b){this.loaded&&this.C.bu.apply(this.C,arguments)};
g.h.aw=function(){return this.loaded?this.C.suggestion:null};
g.h.Qd=function(){return this.o?g7(this.o).Qd:!1};
g.h.hasNext=function(){return this.o?g7(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.J};
g.h.vF=function(){var a=g7(this.o),b=this.g.getVideoData(),c=this.g.wc(),d=b.clipEnd,b=b.clipStart,e=this.getCurrentTime(),f=a.getDuration(),k;k=a.J?a.B+((0,g.C)()-a.A)/1E3:a.B;var l=1>=q6(a)-this.getCurrentTime(),m=a.K,n=q6(a),a=0<a.C?a.C+((0,g.C)()-a.A)/1E3:a.C;return{allowSeeking:c,clipEnd:d,clipStart:b,current:e,displayedStart:-1,duration:f,ingestionTime:k,isPeggedToLive:l,loaded:m,seekableEnd:n,seekableStart:a}};
g.h.wF=function(){this.o&&this.o.dt()};
g.h.xF=function(){this.o&&this.o.gt()};
g.h.Iz=function(a){1==a&&(this.K=this.o?g7(this.o):null)};
g.h.IB=function(){var a=a7()?new f7(w6(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.K=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Kd(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.K)&&a.videoId==this.g.getVideoData().videoId&&this.g.vt(a.videoId,g.ke(a)));this.g.P("videodatachange","newdata",this.g.getVideoData(),3)};
g.h.zr=function(){this.G=[this.A].concat(E7());var a=D7()||this.A;V7(this,a);this.g.pa("onMdxReceiversChange")};
g.h.GB=function(){var a=D7();V7(this,a)};
g.h.FB=function(){this.B=D7()};
g.h.uF=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?H7():V7(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&H7(),!0):!1}};
g.h.yF=function(){h7(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.gd=function(){return!1};window._exportCheck==g.Ea&&g.w("ytmod.player.remote",U7,void 0);})(_yt_player);
