const SAMPLES_DIR = 'samples'

export default {
  '1st Violins (Pizzicato)': [
    { note: 'A#', octave: 3, file: `${SAMPLES_DIR}/1st Violins/1st-violins-piz-rr1-a#3.wav` },
    { note: 'A#', octave: 4, file: `${SAMPLES_DIR}/1st Violins/1st-violins-piz-rr1-a#4.wav` },
    { note: 'A#', octave: 5, file: `${SAMPLES_DIR}/1st Violins/1st-violins-piz-rr1-a#5.wav` },
    { note: 'A#', octave: 6, file: `${SAMPLES_DIR}/1st Violins/1st-violins-piz-rr1-a#6.wav` },
    { note: 'C#', octave: 4, file: `${SAMPLES_DIR}/1st Violins/1st-violins-piz-rr1-c#4.wav` },
    { note: 'C#', octave: 5, file: `${SAMPLES_DIR}/1st Violins/1st-violins-piz-rr1-c#5.wav` },
    { note: 'C#', octave: 6, file: `${SAMPLES_DIR}/1st Violins/1st-violins-piz-rr1-c#6.wav` },
    { note: 'E', octave: 4, file: `${SAMPLES_DIR}/1st Violins/1st-violins-piz-rr1-e4.wav` },
    { note: 'E', octave: 5, file: `${SAMPLES_DIR}/1st Violins/1st-violins-piz-rr1-e5.wav` },
    { note: 'E', octave: 6, file: `${SAMPLES_DIR}/1st Violins/1st-violins-piz-rr1-e6.wav` },
    { note: 'G', octave: 3, file: `${SAMPLES_DIR}/1st Violins/1st-violins-piz-rr1-g3.wav` },
    { note: 'G', octave: 4, file: `${SAMPLES_DIR}/1st Violins/1st-violins-piz-rr1-g4.wav` },
    { note: 'G', octave: 5, file: `${SAMPLES_DIR}/1st Violins/1st-violins-piz-rr1-g5.wav` },
    { note: 'G', octave: 6, file: `${SAMPLES_DIR}/1st Violins/1st-violins-piz-rr1-g6.wav` },
    { note: 'G', octave: 6, file: `${SAMPLES_DIR}/1st Violins/1st-violins-piz-rr1-g6.wav` },
  ],
  '1st Violins (Staccato)': [],
  '1st Violins (Suspended)': [],
  'Alto Flute': [
    { note: 'A#', octave: 3, file: `${SAMPLES_DIR}/Alto Flute/alto_flute-a#3.wav` },
    { note: 'A#', octave: 4, file: `${SAMPLES_DIR}/Alto Flute/alto_flute-a#4.wav` },
    { note: 'A#', octave: 5, file: `${SAMPLES_DIR}/Alto Flute/alto_flute-a#5.wav` },
    { note: 'C#', octave: 4, file: `${SAMPLES_DIR}/Alto Flute/alto_flute-c#4.wav` },
    { note: 'C#', octave: 5, file: `${SAMPLES_DIR}/Alto Flute/alto_flute-c#5.wav` },
    { note: 'C#', octave: 6, file: `${SAMPLES_DIR}/Alto Flute/alto_flute-c#6.wav` },
    { note: 'E', octave: 4, file: `${SAMPLES_DIR}/Alto Flute/alto_flute-e4.wav` },
    { note: 'E', octave: 5, file: `${SAMPLES_DIR}/Alto Flute/alto_flute-e5.wav` },
    { note: 'E', octave: 6, file: `${SAMPLES_DIR}/Alto Flute/alto_flute-e6.wav` },
    { note: 'E', octave: 6, file: `${SAMPLES_DIR}/Alto Flute/alto_flute-e6.wav` },
    { note: 'G', octave: 3, file: `${SAMPLES_DIR}/Alto Flute/alto_flute-g3.wav` },
    { note: 'G', octave: 4, file: `${SAMPLES_DIR}/Alto Flute/alto_flute-g4.wav` },
    { note: 'G', octave: 5, file: `${SAMPLES_DIR}/Alto Flute/alto_flute-g5.wav` },
    { note: 'G', octave: 6, file: `${SAMPLES_DIR}/Alto Flute/alto_flute-g6.wav` },
  ],
  'Bass Clarinet': [
    { note: 'B', octave: 2, file: `${SAMPLES_DIR}/Bass Clarinet/bass_clarinet-b2.wav` },
    { note: 'B', octave: 3, file: `${SAMPLES_DIR}/Bass Clarinet/bass_clarinet-b3.wav` },
    { note: 'B', octave: 4, file: `${SAMPLES_DIR}/Bass Clarinet/bass_clarinet-b4.wav` },
    { note: 'D', octave: 2, file: `${SAMPLES_DIR}/Bass Clarinet/bass_clarinet-d2.wav` },
    { note: 'D', octave: 3, file: `${SAMPLES_DIR}/Bass Clarinet/bass_clarinet-d3.wav` },
    { note: 'D', octave: 4, file: `${SAMPLES_DIR}/Bass Clarinet/bass_clarinet-d4.wav` },
    { note: 'D', octave: 5, file: `${SAMPLES_DIR}/Bass Clarinet/bass_clarinet-d5.wav` },
    { note: 'F', octave: 2, file: `${SAMPLES_DIR}/Bass Clarinet/bass_clarinet-f2.wav` },
    { note: 'F', octave: 3, file: `${SAMPLES_DIR}/Bass Clarinet/bass_clarinet-f3.wav` },
    { note: 'F', octave: 4, file: `${SAMPLES_DIR}/Bass Clarinet/bass_clarinet-f4.wav` },
    { note: 'G#', octave: 2, file: `${SAMPLES_DIR}/Bass Clarinet/bass_clarinet-g#2.wav` },
    { note: 'G#', octave: 3, file: `${SAMPLES_DIR}/Bass Clarinet/bass_clarinet-g#3.wav` },
    { note: 'G#', octave: 4, file: `${SAMPLES_DIR}/Bass Clarinet/bass_clarinet-g#4.wav` },
  ],
  'Bass Trombone': [
    { note: 'A#', octave: 1, file: `${SAMPLES_DIR}/Bass Trombone/bass_trombone-a#1.wav` },
    { note: 'A#', octave: 2, file: `${SAMPLES_DIR}/Bass Trombone/bass_trombone-a#2.wav` },
    { note: 'A#', octave: 3, file: `${SAMPLES_DIR}/Bass Trombone/bass_trombone-a#3.wav` },
    { note: 'C#', octave: 2, file: `${SAMPLES_DIR}/Bass Trombone/bass_trombone-c#2.wav` },
    { note: 'C#', octave: 3, file: `${SAMPLES_DIR}/Bass Trombone/bass_trombone-c#3.wav` },
    { note: 'C#', octave: 4, file: `${SAMPLES_DIR}/Bass Trombone/bass_trombone-c#4.wav` },
    { note: 'E', octave: 1, file: `${SAMPLES_DIR}/Bass Trombone/bass_trombone-e1.wav` },
    { note: 'E', octave: 2, file: `${SAMPLES_DIR}/Bass Trombone/bass_trombone-e2.wav` },
    { note: 'E', octave: 3, file: `${SAMPLES_DIR}/Bass Trombone/bass_trombone-e3.wav` },
    { note: 'E', octave: 4, file: `${SAMPLES_DIR}/Bass Trombone/bass_trombone-e4.wav` },
    { note: 'G', octave: 1, file: `${SAMPLES_DIR}/Bass Trombone/bass_trombone-g1.wav` },
    { note: 'G', octave: 2, file: `${SAMPLES_DIR}/Bass Trombone/bass_trombone-g2.wav` },
    { note: 'G', octave: 3, file: `${SAMPLES_DIR}/Bass Trombone/bass_trombone-g3.wav` },
    { note: 'G', octave: 4, file: `${SAMPLES_DIR}/Bass Trombone/bass_trombone-g4.wav` },
  ],
  'Bassoon': [
    { note: 'A#', octave: 1, file: `${SAMPLES_DIR}/Bassoon/bassoon-a#1.wav` },
    { note: 'A#', octave: 2, file: `${SAMPLES_DIR}/Bassoon/bassoon-a#2.wav` },
    { note: 'A#', octave: 3, file: `${SAMPLES_DIR}/Bassoon/bassoon-a#3.wav` },
    { note: 'A#', octave: 4, file: `${SAMPLES_DIR}/Bassoon/bassoon-a#4.wav` },
    { note: 'C#', octave: 2, file: `${SAMPLES_DIR}/Bassoon/bassoon-c#2.wav` },
    { note: 'C#', octave: 3, file: `${SAMPLES_DIR}/Bassoon/bassoon-c#3.wav` },
    { note: 'C#', octave: 4, file: `${SAMPLES_DIR}/Bassoon/bassoon-c#4.wav` },
    { note: 'C#', octave: 5, file: `${SAMPLES_DIR}/Bassoon/bassoon-c#5.wav` },
    { note: 'E', octave: 2, file: `${SAMPLES_DIR}/Bassoon/bassoon-e2.wav` },
    { note: 'E', octave: 3, file: `${SAMPLES_DIR}/Bassoon/bassoon-e3.wav` },
    { note: 'E', octave: 4, file: `${SAMPLES_DIR}/Bassoon/bassoon-e4.wav` },
    { note: 'G', octave: 2, file: `${SAMPLES_DIR}/Bassoon/bassoon-g2.wav` },
    { note: 'G', octave: 3, file: `${SAMPLES_DIR}/Bassoon/bassoon-g3.wav` },
    { note: 'G', octave: 4, file: `${SAMPLES_DIR}/Bassoon/bassoon-g4.wav` },
  ],
  'Bassoons (Suspended)': [
    { note: 'A#', octave: 1, file: `${SAMPLES_DIR}/Bassoons/bassoons-sus-a#1.wav` },
    { note: 'A#', octave: 2, file: `${SAMPLES_DIR}/Bassoons/bassoons-sus-a#2.wav` },
    { note: 'A#', octave: 3, file: `${SAMPLES_DIR}/Bassoons/bassoons-sus-a#3.wav` },
    { note: 'A#', octave: 4, file: `${SAMPLES_DIR}/Bassoons/bassoons-sus-a#4.wav` },
    { note: 'C#', octave: 2, file: `${SAMPLES_DIR}/Bassoons/bassoons-sus-c#2.wav` },
    { note: 'C#', octave: 3, file: `${SAMPLES_DIR}/Bassoons/bassoons-sus-c#3.wav` },
    { note: 'C#', octave: 4, file: `${SAMPLES_DIR}/Bassoons/bassoons-sus-c#4.wav` },
    { note: 'C#', octave: 5, file: `${SAMPLES_DIR}/Bassoons/bassoons-sus-c#5.wav` },
    { note: 'E', octave: 2, file: `${SAMPLES_DIR}/Bassoons/bassoons-sus-e2.wav` },
    { note: 'E', octave: 3, file: `${SAMPLES_DIR}/Bassoons/bassoons-sus-e3.wav` },
    { note: 'E', octave: 4, file: `${SAMPLES_DIR}/Bassoons/bassoons-sus-e4.wav` },
    { note: 'E', octave: 5, file: `${SAMPLES_DIR}/Bassoons/bassoons-sus-e5.wav` },
    { note: 'G', octave: 2, file: `${SAMPLES_DIR}/Bassoons/bassoons-sus-g2.wav` },
    { note: 'G', octave: 3, file: `${SAMPLES_DIR}/Bassoons/bassoons-sus-g3.wav` },
    { note: 'G', octave: 4, file: `${SAMPLES_DIR}/Bassoons/bassoons-sus-g4.wav` },
  ],
  'Cello': [
    { note: 'A', octave: 2, file: `${SAMPLES_DIR}/Cello/cello-a2.wav` },
    { note: 'A', octave: 3, file: `${SAMPLES_DIR}/Cello/cello-a3.wav` },
    { note: 'A', octave: 4, file: `${SAMPLES_DIR}/Cello/cello-a4.wav` },
    { note: 'A', octave: 5, file: `${SAMPLES_DIR}/Cello/cello-a5.wav` },
    { note: 'C', octave: 2, file: `${SAMPLES_DIR}/Cello/cello-c2.wav` },
    { note: 'C', octave: 3, file: `${SAMPLES_DIR}/Cello/cello-c3.wav` },
    { note: 'C', octave: 4, file: `${SAMPLES_DIR}/Cello/cello-c4.wav` },
    { note: 'C', octave: 5, file: `${SAMPLES_DIR}/Cello/cello-c5.wav` },
    { note: 'D#', octave: 2, file: `${SAMPLES_DIR}/Cello/cello-d#2.wav` },
    { note: 'D#', octave: 3, file: `${SAMPLES_DIR}/Cello/cello-d#3.wav` },
    { note: 'D#', octave: 4, file: `${SAMPLES_DIR}/Cello/cello-d#4.wav` },
    { note: 'D#', octave: 5, file: `${SAMPLES_DIR}/Cello/cello-d#5.wav` },
    { note: 'F#', octave: 2, file: `${SAMPLES_DIR}/Cello/cello-f#2.wav` },
    { note: 'F#', octave: 3, file: `${SAMPLES_DIR}/Cello/cello-f#3.wav` },
    { note: 'F#', octave: 4, file: `${SAMPLES_DIR}/Cello/cello-f#4.wav` },
    { note: 'F#', octave: 5, file: `${SAMPLES_DIR}/Cello/cello-f#5.wav` }
  ],
  'Chorus': [
    { note: 'A', octave: 2, file: `${SAMPLES_DIR}/Chorus/chorus-male-a2.wav` },
    { note: 'A', octave: 3, file: `${SAMPLES_DIR}/Chorus/chorus-male-a3.wav` },
    { note: 'A', octave: 4, file: `${SAMPLES_DIR}/Chorus/chorus-female-a4.wav` },
    { note: 'A', octave: 5, file: `${SAMPLES_DIR}/Chorus/chorus-female-a5.wav` },
    { note: 'A#', octave: 2, file: `${SAMPLES_DIR}/Chorus/chorus-male-a#2.wav` },
    { note: 'A#', octave: 3, file: `${SAMPLES_DIR}/Chorus/chorus-male-a#3.wav` },
    { note: 'A#', octave: 4, file: `${SAMPLES_DIR}/Chorus/chorus-female-a#4.wav` },
    { note: 'A#', octave: 5, file: `${SAMPLES_DIR}/Chorus/chorus-female-a#5.wav` },
    { note: 'B', octave: 2, file: `${SAMPLES_DIR}/Chorus/chorus-male-b2.wav` },
    { note: 'B', octave: 3, file: `${SAMPLES_DIR}/Chorus/chorus-male-b3.wav` },
    { note: 'B', octave: 4, file: `${SAMPLES_DIR}/Chorus/chorus-female-b4.wav` },
    { note: 'B', octave: 5, file: `${SAMPLES_DIR}/Chorus/chorus-female-b5.wav` },
    { note: 'C', octave: 3, file: `${SAMPLES_DIR}/Chorus/chorus-male-c3.wav` },
    { note: 'C', octave: 4, file: `${SAMPLES_DIR}/Chorus/chorus-male-c4.wav` },
    { note: 'C', octave: 5, file: `${SAMPLES_DIR}/Chorus/chorus-female-c5.wav` },
    { note: 'C', octave: 6, file: `${SAMPLES_DIR}/Chorus/chorus-female-c6.wav` },
    { note: 'C#', octave: 3, file: `${SAMPLES_DIR}/Chorus/chorus-male-c#3.wav` },
    { note: 'C#', octave: 4, file: `${SAMPLES_DIR}/Chorus/chorus-male-c#4.wav` },
    { note: 'C#', octave: 5, file: `${SAMPLES_DIR}/Chorus/chorus-female-c#5.wav` },
    { note: 'D', octave: 3, file: `${SAMPLES_DIR}/Chorus/chorus-male-d3.wav` },
    { note: 'D', octave: 4, file: `${SAMPLES_DIR}/Chorus/chorus-male-d4.wav` },
    { note: 'D', octave: 5, file: `${SAMPLES_DIR}/Chorus/chorus-female-d5.wav` },
    { note: 'D#', octave: 3, file: `${SAMPLES_DIR}/Chorus/chorus-male-d#3.wav` },
    { note: 'D#', octave: 4, file: `${SAMPLES_DIR}/Chorus/chorus-male-d#4.wav` },
    { note: 'D#', octave: 5, file: `${SAMPLES_DIR}/Chorus/chorus-female-d#5.wav` },
    { note: 'E', octave: 3, file: `${SAMPLES_DIR}/Chorus/chorus-male-e3.wav` },
    { note: 'E', octave: 4, file: `${SAMPLES_DIR}/Chorus/chorus-male-e4.wav` },
    { note: 'E', octave: 5, file: `${SAMPLES_DIR}/Chorus/chorus-female-e5.wav` },
    { note: 'F', octave: 3, file: `${SAMPLES_DIR}/Chorus/chorus-male-f3.wav` },
    { note: 'F', octave: 4, file: `${SAMPLES_DIR}/Chorus/chorus-male-f4.wav` },
    { note: 'F', octave: 5, file: `${SAMPLES_DIR}/Chorus/chorus-female-f5.wav` },
    { note: 'F#', octave: 3, file: `${SAMPLES_DIR}/Chorus/chorus-male-f#3.wav` },
    { note: 'F#', octave: 4, file: `${SAMPLES_DIR}/Chorus/chorus-male-f#4.wav` },
    { note: 'F#', octave: 5, file: `${SAMPLES_DIR}/Chorus/chorus-female-f#5.wav` },
    { note: 'G', octave: 2, file: `${SAMPLES_DIR}/Chorus/chorus-male-g2.wav` },
    { note: 'G', octave: 3, file: `${SAMPLES_DIR}/Chorus/chorus-male-g3.wav` },
    { note: 'G', octave: 4, file: `${SAMPLES_DIR}/Chorus/chorus-female-g4.wav` },
    { note: 'G', octave: 5, file: `${SAMPLES_DIR}/Chorus/chorus-female-g5.wav` },
    { note: 'G#', octave: 2, file: `${SAMPLES_DIR}/Chorus/chorus-male-g#2.wav` },
    { note: 'G#', octave: 3, file: `${SAMPLES_DIR}/Chorus/chorus-male-g#3.wav` },
    { note: 'G#', octave: 4, file: `${SAMPLES_DIR}/Chorus/chorus-female-g#4.wav` },
    { note: 'G#', octave: 5, file: `${SAMPLES_DIR}/Chorus/chorus-female-g#5.wav` },
  ],
  'Grand Piano': [
    { note: 'A', octave: 4, file: `${SAMPLES_DIR}/Grand Piano/piano-f-a4.wav` },
    { note: 'A',  octave: 5, file: `${SAMPLES_DIR}/Grand Piano/piano-f-a5.wav` },
    { note: 'A',  octave: 6, file: `${SAMPLES_DIR}/Grand Piano/piano-f-a6.wav` },
    { note: 'C',  octave: 4, file: `${SAMPLES_DIR}/Grand Piano/piano-f-c4.wav` },
    { note: 'C',  octave: 5, file: `${SAMPLES_DIR}/Grand Piano/piano-f-c5.wav` },
    { note: 'C',  octave: 6, file: `${SAMPLES_DIR}/Grand Piano/piano-f-c6.wav` },
    { note: 'D#',  octave: 4, file: `${SAMPLES_DIR}/Grand Piano/piano-f-d#4.wav` },
    { note: 'D#',  octave: 5, file: `${SAMPLES_DIR}/Grand Piano/piano-f-d#5.wav` },
    { note: 'D#',  octave: 6, file: `${SAMPLES_DIR}/Grand Piano/piano-f-d#6.wav` },
    { note: 'F#',  octave: 4, file: `${SAMPLES_DIR}/Grand Piano/piano-f-f#4.wav` },
    { note: 'F#',  octave: 5, file: `${SAMPLES_DIR}/Grand Piano/piano-f-f#5.wav` },
    { note: 'F#',  octave: 6, file: `${SAMPLES_DIR}/Grand Piano/piano-f-f#6.wav` }
  ],
  'Harp': [
    { note: 'A', octave: 2, file: `${SAMPLES_DIR}/Harp/harp-a2.wav` },
    { note: 'A', octave: 3, file: `${SAMPLES_DIR}/Harp/harp-a3.wav` },
    { note: 'A', octave: 4, file: `${SAMPLES_DIR}/Harp/harp-a4.wav` },
    { note: 'A', octave: 5, file: `${SAMPLES_DIR}/Harp/harp-a5.wav` },
    { note: 'A', octave: 6, file: `${SAMPLES_DIR}/Harp/harp-a6.wav` },
    { note: 'C', octave: 2, file: `${SAMPLES_DIR}/Harp/harp-c2.wav` },
    { note: 'C', octave: 3, file: `${SAMPLES_DIR}/Harp/harp-c3.wav` },
    { note: 'C', octave: 4, file: `${SAMPLES_DIR}/Harp/harp-c4.wav` },
    { note: 'C', octave: 5, file: `${SAMPLES_DIR}/Harp/harp-c5.wav` },
    { note: 'C', octave: 6, file: `${SAMPLES_DIR}/Harp/harp-c6.wav` },
    { note: 'C', octave: 7, file: `${SAMPLES_DIR}/Harp/harp-c7.wav` },
    { note: 'D#', octave: 2, file: `${SAMPLES_DIR}/Harp/harp-d#2.wav` },
    { note: 'D#', octave: 3, file: `${SAMPLES_DIR}/Harp/harp-d#3.wav` },
    { note: 'D#', octave: 4, file: `${SAMPLES_DIR}/Harp/harp-d#4.wav` },
    { note: 'D#', octave: 5, file: `${SAMPLES_DIR}/Harp/harp-d#5.wav` },
    { note: 'D#', octave: 6, file: `${SAMPLES_DIR}/Harp/harp-d#6.wav` },
    { note: 'F#', octave: 2, file: `${SAMPLES_DIR}/Harp/harp-f#2.wav` },
    { note: 'F#', octave: 3, file: `${SAMPLES_DIR}/Harp/harp-f#3.wav` },
    { note: 'F#', octave: 4, file: `${SAMPLES_DIR}/Harp/harp-f#4.wav` },
    { note: 'F#', octave: 5, file: `${SAMPLES_DIR}/Harp/harp-f#5.wav` },
    { note: 'F#', octave: 6, file: `${SAMPLES_DIR}/Harp/harp-f#6.wav` }
  ],
  'Violin': [
    { note: 'A#', octave: 3, file: `${SAMPLES_DIR}/Violin/violin-a#3.wav` },
    { note: 'A#', octave: 4, file: `${SAMPLES_DIR}/Violin/violin-a#4.wav` },
    { note: 'A#', octave: 5, file: `${SAMPLES_DIR}/Violin/violin-a#5.wav` },
    { note: 'A#', octave: 6, file: `${SAMPLES_DIR}/Violin/violin-a#6.wav` },
    { note: 'C#', octave: 4, file: `${SAMPLES_DIR}/Violin/violin-c#4.wav` },
    { note: 'C#', octave: 5, file: `${SAMPLES_DIR}/Violin/violin-c#5.wav` },
    { note: 'C#', octave: 6, file: `${SAMPLES_DIR}/Violin/violin-c#6.wav` },
    { note: 'C#', octave: 7, file: `${SAMPLES_DIR}/Violin/violin-c#7.wav` },
    { note: 'E', octave: 4, file: `${SAMPLES_DIR}/Violin/violin-e4.wav` },
    { note: 'E', octave: 5, file: `${SAMPLES_DIR}/Violin/violin-e5.wav` },
    { note: 'E', octave: 6, file: `${SAMPLES_DIR}/Violin/violin-e6.wav` },
    { note: 'G', octave: 3, file: `${SAMPLES_DIR}/Violin/violin-g3.wav` },
    { note: 'G', octave: 4, file: `${SAMPLES_DIR}/Violin/violin-g4.wav` },
    { note: 'G', octave: 5, file: `${SAMPLES_DIR}/Violin/violin-g5.wav` },
    { note: 'G', octave: 6, file: `${SAMPLES_DIR}/Violin/violin-g6.wav` }
  ]
}
